=== JoaoPedroMaFi/Isi2122/fileSamples/xml3Validation.dtd
<!--elements-->
  <!ELEMENT isolados (isolado+)>
  <!ELEMENT isolado (idequipa, firstname, laststname, respeitou)>
  <!ELEMENT idequipa (#PCDATA)>
  <!ELEMENT firstname (#PCDATA)>
  <!ELEMENT laststname (#PCDATA)>
  <!ELEMENT respeitou (#PCDATA)>


  <!--attributes-->
  <!ATTLIST isolados data CDATA #REQUIRED>
  <!ATTLIST isolado id CDATA #REQUIRED>

=== JoaoPedroMaFi/Isi2122/fileSamples/xml3 - Cópia.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE isolados SYSTEM "xml3Validation.dtd">
<isolados data="2021-09-30">
	<isolado utentNumber="25498763">
		<idequipa>1</idequipa>
		<firstname>Joao</firstname>
    <lastname>Figueiredo</lastname>
		<respeitou>false</respeitou>
	</isolado>
	<isolado utentNumber="245374346">
		<idequipa>2</idequipa>
		<firstname>Yuri</firstname>
    <lastname>Lemos</lastname>
		<respeitou>false</respeitou>
	</isolado>
	<isolado utentNumber="712344389">
		<idequipa>3</idequipa>
		<firstname>Andre</firstname>
    <lastname>Felicidade</lastname>
		<respeitou>false</respeitou>
	</isolado>
</isolados>

=== JoaoPedroMaFi/Isi2122/fileSamples/xml3.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE isolados SYSTEM "xml3Validation.dtd">
<isolados data="2021-09-31">
	<isolado utentNumber="17464754">
		<idequipa>1</idequipa>
		<firstname>primeiro</firstname>
    <lastname>primeiroApelido</lastname>
		<respeitou>true</respeitou>
	</isolado>
	<isolado utentNumber="245365346">
		<idequipa>2</idequipa>
		<firstname>segundo</firstname>
    <lastname>segundoApelido</lastname>
		<respeitou>false</respeitou>
	</isolado>
	<isolado utentNumber="734364389">
		<idequipa>3</idequipa>
		<firstname>terceiro</firstname>
    <lastname>terceiroApelido</lastname>
		<respeitou>true</respeitou>
	</isolado>
</isolados>
